[project]
name = "persnal-library-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit==1.43.2"
    "pandas==2.2.3"
    "plotly==6.0.0"
]
