[project]
name = "personal-library-manager" 
version = "0.1.0"
description = "A personal library management application built with Streamlit"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit==1.43.2",  
    "pandas==2.2.3",      
    "plotly==6.0.0"       
]